sonar.projectKey=github-action-python-3Tier

sonar.projectName=github-action-python-3Tier

sonar.projectVersion=1.0

sonar.sources=backend,frontend

sonar.sourceEncoding=UTF-8

sonar.python.version=3.11

sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.git/**
