AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7ABCDEF"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY1"
GITHUB_TOKEN = "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"
DB_PASSWORD = "SuperSecretPassword123!"
