AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7ABCDEF"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY1"
GITHUB_TOKEN = "ghp_Ejkec09cjd889fd89cc89c8sDAsa8saDSDsdada9Sfad"
DB_PASSWORD = "SuperSecretPassword123!"
