AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7ABCDEF"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY1"
GITHUB_TOKEN = "ghp_1234567890abcdefghijklmnopqrstuvwxyz"
DB_PASSWORD = "SuperSecretPassword123!"
