name: DevSecOps

on: 
  push:
    branches: [main]

jobs:
  # Code Lint Check
#  Code-Linting:
#   uses: ./.github/workflows/lint.yml


#  Gitleaks:
    # needs: Code-Linting
#    uses: ./.github/workflows/gitleaks.yml

# ----Sast Scan -----
  Sast-Scan:
    uses: ./.github/workflows/sast.yml



  
