name: DevSecOps

on: 
  push:
    branches: [main]

jobs:

  # Code-Linting:
  #   uses: ./.github/workflows/lint.yml

  # GitLeaks:
  #   needs: Code-Linting
  #   uses: ./.github/workflows/gitleaks.yml

  # SAST:
  #   needs: GitLeaks
  #   uses: ./.github/workflows/sast.yml

  # SCA:
  #   needs: SAST
  #   uses: ./.github/workflows/sca.yml

   Docker-Build:
    # #needs: SCA
      uses: ./.github/workflows/docker-push.yml
      secrets: inherit

   Trivy-Scan:
      needs:    Docker-Build
      uses: ./.github/workflows/trivy-image.yml
  
