name: DevSecOps

on:
  push:
    branches:
      - main

jobs:

  # 1. Code Quality
  Code-Linting:
    uses: ./.github/workflows/lint.yml

  # 2. Secret Detection
  GitLeaks:
    needs: Code-Linting
    uses: ./.github/workflows/gitleaks.yml

  # 3. Static Security Testing
  SAST:
    needs: GitLeaks
    uses: ./.github/workflows/sast.yml

  # 4. Dependency Security
  SCA:
    needs: SAST
    uses: ./.github/workflows/sca.yml

  # 5. Unit Tests
  Code-Test:
    needs: SCA
    uses: ./.github/workflows/code-test.yml

  # 6. SonarQube Analysis
  Sonar-Scan:
    needs: Code-Test
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit

  # 7. Docker Build + Hadolint + Push
  Docker-Build:
    needs: Sonar-Scan
    uses: ./.github/workflows/docker-Hadolint-Login-push.yml
    secrets: inherit

  # 8. Trivy Image Scan
  Trivy-Scan:
    needs: Docker-Build
    uses: ./.github/workflows/trivy-image.yml


#######--------CD---------#####
  # 9. Deploy stage. Before this only do the CI steps now this is the CD step to deploy on live server.This make the Complete CI/CD pipeline.   
  Deploy-CD:
    needs: Trivy-Scan
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  # 10. Dynamic Security Testing
  DAST:
    needs: Deploy-CD
    uses: ./.github/workflows/dast.yml
    secrets: inherit
