name: GitLeaks Scan

on:
  workflow_call:

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
        # Depth use with Zero "0"  it scan all the commit history from stater of Git init.
          fetch-depth: 0   

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v3

      - name: Upload Report to Artifacts
        if: always() # Ensures report uploads even if tests fail
        uses: actions/upload-artifact@v4
        with:
            name: Secret-Scanning
            path: reports/gitleaks-report.txt
            retention-days: 5
