name: SAST Scan

on:
  workflow_call: 
    

jobs:
  sast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Python SAST scan
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        # This scans the current directory, ignoring tests, and outputs a report
        run: bandit -r . -x ./tests -v
        working-directory: backend

      - name: Run Semgrep SAST Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: p/javascript
        
