name: SAST Scan

on:
  workflow_call: 

jobs:
  sast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan (Backend - Python)
        # Scans backend directory for Python security issues
        run: bandit -r . -x ./tests -v --exit-zero
        working-directory: backend

      - name: Run Semgrep SAST Scan (Backend - Python)
        uses: semgrep/semgrep-action@v1
        continue-on-error: true
        with:
          config: p/python

      - name: Run Semgrep SAST Scan (Frontend - JavaScript)
        uses: semgrep/semgrep-action@v1
        with:
          config: p/javascript
        env:
          SEMGREP_RULES: p/javascript
